name: ruqqus_dart
description: A powerful Dart library for interacting with the Ruqqus API.
version: 1.0.2

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  ansicolor: ^1.0.5
  dio: ^3.0.10
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.9.0

