name: ruqqus_dart
version: 3.1.2
description: >-
  Fully-documented, powerful and extensive interface to interact 
  with the Ruqqus API written in Dart
author: Dorian OszczÄ™da <vxern@wordcollector.co.uk>
homepage: https://github.com/vxern/ruqqus_dart
repository: https://github.com/vxern/ruqqus_dart
#documentation:
issue_tracker: https://github.com/vxern/ruqqus_dart/issues

publish_to: https://pub.dev

environment:
  sdk: '>=2.13.3 <3.0.0'

dependencies:
  # Core
  http: ^0.13.3
  event_dart: ^2.0.1

  # Logging
  sprint: ^1.0.1

  # Date formatting
  enum_to_string: ^2.0.1
